#image: registry.gitlab.com/pages/hugo:latest
#image: klakegg/hugo:alpine
image: monachus/hugo

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - apt update
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
