#image: registry.gitlab.com/pages/hugo:latest
#image: klakegg/hugo:alpine
image: monachus/hugo

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

#test:
#  script:
#  - hugo version
#  - hugo
#  except:
#  - master

pages:
  script:
  #- apk update
  #- apk add hugo
  - apt-get update
  - apt-get install openssh-client
  - hugo version
  - hugo
  - echo $(date +%Y.%m.%d)
  - scp -r public gitlab@hsbxl.be:/srv/www/hsbxl.be/www/versions/$(date +%Y.%m.%d)/
  artifacts:
    paths:
    - public
  only:
  - master
