#image: registry.gitlab.com/pages/hugo:latest
#image: klakegg/hugo:alpine
image: monachus/hugo

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

#test:
#  script:
#  - hugo version
#  - hugo
#  except:
#  - master


before_script:
  - apt-get update
  - apt-get install openssh-client -y
  - eval $(ssh-agent -s)
  - echo "$PRIVKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


pages:
  variables:
    GITLAB_USER_LOGIN: $GITLAB_USER_LOGIN
    CI_BUILD_REF: $CI_BUILD_REF
  script:
  #- apk update
  #- apk add hugo
  - hugo version
  - hugo
  - echo $(date +%Y.%m.%d)
  - tar cz public | ssh gitlab@hsbxl.be "mkdir -p /www/versions/$(date +%Y.%m.%d); cd /www/versions/$(date +%Y.%m.%d); tar xz; rm /www/live; ln -sf versions/$(date +%Y.%m.%d)/public /www/live"
  #- source scripts/matrixlog.sh
  - curl "https://hackerspaces.be/_matrix/client/r0/rooms/!mnQLxCDhwmKozNmuIB:hackerspaces.be/send/m.room.message?access_token=MDAxZGxvY2F0aW9uIGhhY2tlcnNwYWNlcy5iZQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMmFjaWQgdXNlcl9pZCA9IEBnaXRsYWI6aGFja2Vyc3BhY2VzLmJlCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0geXgrNUJZK211aWk0dnN5dQowMDJmc2lnbmF0dXJlIOEs7nsIv4K9Fj1mhcnGjkbwxHn-Y13vSlNz6kcVGKYjCg" -X POST -H 'Content-Type: application/json' -d '{"msgtype":"m.text", "body": "'"$CI_BUILD_REF"'" }'


  #- curl -XPOST -d '{"msgtype":"m.text", "body":"Website updated by "'"$GITLAB_USER_LOGIN"'" "'"$CI_COMMIT_MESSAGE"'""}' "https://hackerspaces.be/_matrix/client/r0/rooms/!mnQLxCDhwmKozNmuIB:hackerspaces.be/send/m.room.message?access_token=$MATRIX_ACCESS_TOKEN"
  #- curl -X POST -d '{"msgtype":"m.text", "body":"hello world" } ' -H "Content-Type: application/json" "https://hackerspaces.be/_matrix/client/r0/rooms/!mnQLxCDhwmKozNmuIB:hackerspaces.be/send/m.room.message?access_token=MDAxZGxvY2F0aW9uIGhhY2tlcnNwYWNlcy5iZQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMmFjaWQgdXNlcl9pZCA9IEBnaXRsYWI6aGFja2Vyc3BhY2VzLmJlCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0geXgrNUJZK211aWk0dnN5dQowMDJmc2lnbmF0dXJlIOEs7nsIv4K9Fj1mhcnGjkbwxHn-Y13vSlNz6kcVGKYjCg"
  #- scp -r public gitlab@hsbxl.be:/srv/www/hsbxl.be/www/versions/$(date +%Y.%m.%d)/
  #- ssh gitlab@hsbxl.be "rm /www/live; ln -sf versions/$(date +%Y.%m.%d)/public /www/live"
  artifacts:
    paths:
    - public
  only:
  - master
