#image: registry.gitlab.com/pages/hugo:latest
#image: klakegg/hugo:alpine
image: monachus/hugo

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

#test:
#  script:
#  - hugo version
#  - hugo
#  except:
#  - master


before_script:
  - apt-get update
  - apt-get install openssh-client -y
  - eval $(ssh-agent -s)
  - echo "$PRIVKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


pages:
  script:
  #- apk update
  #- apk add hugo
  - hugo version
  - hugo
  - echo $(date +%Y.%m.%d)
  - tar cz public | ssh gitlab@hsbxl.be "mkdir -p /www/versions/$(date +%Y.%m.%d); cd /www/versions/$(date +%Y.%m.%d); tar xz; rm /www/live; ln -sf versions/$(date +%Y.%m.%d)/public /www/live"
  #- scp -r public gitlab@hsbxl.be:/srv/www/hsbxl.be/www/versions/$(date +%Y.%m.%d)/
  #- ssh gitlab@hsbxl.be "rm /www/live; ln -sf versions/$(date +%Y.%m.%d)/public /www/live"
  artifacts:
    paths:
    - public
  only:
  - master
