#image: registry.gitlab.com/pages/hugo:latest
#image: klakegg/hugo:alpine
image: monachus/hugo

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo version
  - hugo
  except:
  - master

pages:
script:
  #- apt-get update
  #- apt-get install cadaver -y
  - hugo version
  - hugo
  #- ./scripts/copy_webdav.sh public https://hsbxl.be/dav/versions
  artifacts:
    paths:
    - public
  only:
  - master
