baseurl = "https://example.org/"
languageCode = "en-us"
title = "HSBXL AGENDA"
theme = "code-editor"

sectionPagesMenu = "main"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Your name"
	description = "Describe your website"
	copyright = ""

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hackerspace Brussels"
	bio = "is a space, dedicated to various aspects of constructive & creative hacking. The space is about 300 square meters, there is a little electronics lab with over 9000 components, a library, and lots of tools. You're always welcome to follow one of the workshops or come to the weekly Tuesday meetings, hack nights or other get-together events."
	subscribe = "Subscribe"
	followme = "Follow us on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
    		name = "Gitlab"
    		url = "https://gitlab.com/hsbxl"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "https://github.com/hsbxl"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "https://twitter.com/hsbxl"
    [[params.offcanvas.socialnetworks]]
        name = "Facebook"
        url = "https://www.facebook.com/groups/hsbxl"
